# Routes USER

# BLOG
ruralis_homepage: #Liste tous les articles
    path:     /
    defaults: { _controller: RuralisBundle:ViewsUser:ruralis }


ruralis_article: #Affiche un article
    path:     /{id}/article
    defaults: { _controller: RuralisBundle:ViewsUser:article, id: null }

# RURALIS
ruralis_presentation:
    path:     /blog
    defaults: { _controller: RuralisBundle:ViewsUser:index, page:1 }

# PARTENAIRES
ruralis_partenaire:
    path:     /partenaires
    defaults: { _controller: RuralisBundle:ViewsUser:partenaires }

# ABONNMENT
ruralis_abonnement:
    path:     /abonnement
    defaults: { _controller: RuralisBundle:ViewsUser:abonnement }

ruralis_formulaire_abonnement:
    path:     /{type}/formulaire
    defaults: { _controller: RuralisBundle:Formulaire:index, type: lecteur|donateur|ambassadeur}
    requirements:
        type: lecteur|donateur|ambassadeur

ruralis_recapitulatif_abo:
    path:     /recapitulatif
    defaults: { _controller:  RuralisBundle:Formulaire:recapAbo}
    methods:  [POST]

ruralis_abosend:
    path:     /validationabonnement
    defaults: { _controller:  RuralisBundle:Contact:abosend, details: null }
    methods:  [GET, POST]

ruralis_aboannul:
    path:     /annulationabonnement
    defaults: { _controller:  RuralisBundle:Contact:aboannul}
    methods:  [GET, POST]

ruralis_cadeau:
    path:     /formulaire/cadeau
    defaults: { _controller: RuralisBundle:ViewsUser:cadeau, cadeau: true }

# NEWSLETTER
ruralis_inscription_newsletter:
    path:     /inscriptionnewsletter
    defaults: { _controller:  RuralisBundle:Contact:inscription}
    methods:  [GET, POST]

ruralis_desinscription_news:
    path:     /desinscriptionNewsletter
    defaults:  { _controller: RuralisBundle:Contact:desinscriptionNews }

ruralis_confirmation_desinscription_news:
    path:     /confirmationDesinscriptionNewsletter
    defaults:  { _controller: RuralisBundle:Contact:confirmDesinscriptionNews }
